services:
  app:
    build:
      context: .
      dockerfile: ./manager/docker/Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    container_name: evo
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./manager/docker/php.ini:/usr/local/etc/php/php.ini
      - ./manager/docker/msmtprc:/etc/msmtprc:ro
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db
      - mailpit
    networks:
      - evo_net

  db:
    image: mysql:8.3
    container_name: evo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-evo}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - db_data_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - evo_net

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - evo_net

networks:
  evo_net:
    driver: bridge

volumes:
  db_data_mysql:
