REPLACE INTO `{PREFIX}site_content` VALUES (1, 'document', 'text/html', 'Home', 'Welcome to MODX', 'Introduction to MODX', 'index', '', 1, 0, 0, 0, 0, 'Create and do amazing things with MODX', '<h3>MODXへようこそ!</h3>\r\n<p>\r\nこのサンプルサイトが個性的なウェブサイトを構築するためのヒントになれば幸いです。\r\n</p>\r\n<ul>\r\n	<li><strong>簡易ブログ</strong><br />\r\n	新着情報の更新に利用するのもよいでしょう。 <a href=\"[~2~]\">サンプルブログを見る</a></li>\r\n	<li><strong>コメント機能</strong><br />\r\n	サイトの登録ユーザーがあなたの記事にコメントすることができます。 <a href=\"[~9~]\">表示例</a></li>\r\n	<li><strong>RSSフィード</strong><br />\r\n	RSSフィードは、あなたのサイトに訪れた人に最新の情報を提供します。 <a href=\"[(site_url)][~11~]\">RSSフィードを見る</a></li>\r\n	<li><strong>自動ユーザー登録</strong><br />\r\n	ブログにコメントする場合は最初にアカウントを作成します。登録フォームには、画像認証によるスパム防止機能があらかじめ装備されています。 <a href=\"[~5~]\">登録フォームを見る</a></li>\r\n	<li><strong>QuickManager（クイックマネージャー）</strong><br />\r\n	マネージャーにログインしている状態なら、実際に表示されているページを見ながらダイレクトに編集できます。 <a href=\"[~14~]\">コンテンツ管理をもっと見る</a></li>\r\n	<li><strong>強力なナビゲーション生成機能</strong><br />\r\n	ダイナミックメニュービルダーを使えば、このサンプルの上部メニューのような様々な種類のナビゲーションを複製・作成することができます。 <a href=\"[~22~]\">メニューについてもっと見る</a></li>\r\n	<li><strong>Mootools</strong><strong>（Ajaxライブラリ）</strong><br />\r\n	Web2.0とAjaxの先端技術がつまってます。 <a href=\"[~16~]\">Ajaxについてもっと見る</a></li>\r\n	<li><strong>エラーページ(page not found[404])をカスタマイズ</strong><br />\r\n	探し物をして迷子になった閲覧者を助けてあげてください。 <a href=\"[~7~]\">404ページを見る</a></li>\r\n	<li><strong>コンタクトフォーム</strong><br />\r\n	コンタクトフォームの高度な設定機能を使って正しいアドレスにメールが配送されるように設定することができます。また、メールフォームへの攻撃防止機能が、スパムメールの踏み台にされることを防ぎます。 <a href=\"[~6~]\">コンタクトフォームを見る</a></li>\r\n</ul>\r\n<p>\r\n<strong>MODXのコントロールパネルへログインしてこのサイトをカスタマイズするために、 <a href=\"manager\">[(site_url)]manager/</a>をブラウズしてください。</strong>\r\n</p>', 1, 4, 1, 1, 1, 1, 1144904400, 1, 1160262629, 0, 0, 0, 0, 0, 'Home', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (2, 'document', 'text/html', 'ブログ', 'ブログエントリー', '', 'blog', '', 1, 0, 0, 0, 1, '', '[[Ditto? &parents=`2` &display=`2` &removeChunk=`Comments` &tpl=`ditto_blog` &paginate=`1` &extenders=`summary,dateFilter` &paginateAlwaysShowLinks=`1` &tagData=`documentTags` &id=`wp`]]\r\n\r\n<p>Showing <strong>[+wp_start+]</strong> - <strong>[+wp_stop+]</strong> of <strong>[+wp_total+]</strong> Articles</p>\r\n\r\n<div id="ditto_pages"> [+wp_previous+] [+wp_pages+] [+wp_next+] </div>\r\n\r\n<div id="ditto_pages">&nbsp;</div>\r\n\r\n[[Reflect? &config=`wordpress` &dittoSnippetParameters=`parents:2` &id=`wp` &getDocuments=`1`]]', 1, 4, 2, 0, 0, 1, 1144904400, 1, 1159818696, 0, 0, 0, 0, 0, 'ブログ', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (4, 'document', 'text/html', '[*loginName*]', 'コメントを書くにはログインしてください。', '', 'login', '', 1, 0, 0, 0, 0, '', '<p>ブログのエントリーにコメントを残したいときには、[(site_name)]にユーザー登録されている必要があります。まだ登録していないときは、 <a href=\"[~5~]\">申請をしてください。</a>.</p>\r\n<div> [!WebLogin? &tpl=`WebLoginSideBar` &loginhomeid=`2`!] </div>', 1, 4, 11, 0, 0, 1, 1144904400, 1, 1144904400, 0, 0, 0, 0, 0, '[*loginName*]', 0, 0, 0, 0, 0, 0, 1);


REPLACE INTO `{PREFIX}site_content` VALUES (5, 'document', 'text/html', 'アカウントの登録申請', 'アカウント情報を入力してください。', '', 'request-an-account', '', 1, 0, 0, 0, 0, '', '[[WebSignup? &tpl=`FormSignup` &groups=`Registered Users`]]', 1, 4, 3, 0, 0, 1, 1144904400, 1, 1158320704, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 1);


REPLACE INTO `{PREFIX}site_content` VALUES (6, 'document', 'text/html', 'お問い合わせ', 'お問い合わせ [(site_name)]', '', 'contact-us', '', 1, 0, 0, 0, 0, '', '[!eForm? &formid=`ContactForm` &subject=`[+subject+]` &to=`[(emailsender)]` &ccsender=`1` &tpl=`ContactForm` &report=`ContactFormReport` &invalidClass=`invalidValue` &requiredClass=`requiredValue` &cssStyle=`ContactStyles` &gotoid=`46`  !]\r\n', 0, 4, 14, 1, 0, 1, 1144904400, 1, 1159303922, 0, 0, 0, 0, 0, 'お問い合わせ', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (7, 'document', 'text/html', '404 - Document Not Found', 'お探しのページが見当たりません (Page Not Found)', '', 'doc-not-found', '', 1, 0, 0, 0, 0, '', '<p>\r\n存在しないページへアクセスしたようです。 ログインするか、 以下のページにアクセスしてください:\r\n</p>\r\n[[Wayfinder? &startId=`0` &showDescription=`1`]]\r\n\r\n<h3>または、サイト上部の検索機能を使ってお探しのページを検索してください。</h3>\r\n\r\n', 1, 4, 4, 0, 1, 1, 1144904400, 1, 1159301173, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 1);


REPLACE INTO `{PREFIX}site_content` VALUES (8, 'document', 'text/html', '検索結果', '検索結果', '', 'search-results', '', 1, 0, 0, 0, 0, '', '[!AjaxSearch? &showInputForm=`0` &ajaxSearch=`0`!]', 0, 4, 5, 0, 0, 1, 1144904400, 1, 1158613055, 0, 0, 0, 0, 0, '', 1, 0, 0, 0, 0, 0, 1);

REPLACE INTO `{PREFIX}site_content` VALUES (11, 'document', 'application/rss+xml', 'RSS フィード', '[(site_name)] RSSフィード', '', 'feed.rss', '', 1, 0, 0, 0, 0, '', '[[Ditto? &parents=`2` &format=`rss` &display=`20` &total=`20` &removeChunk=`Comments`]]', 0, 0, 6, 0, 0, 1, 1144904400, 1, 1160062859, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 1);


REPLACE INTO `{PREFIX}site_content` VALUES (14, 'document', 'text/html', 'コンテンツ管理', 'コンテンツマネージメント', '', 'cms', '', 1, 0, 0, 15, 0, '', '<h2管理画面からコンテンツ管理</h2>\r\n<p>MODXの管理画面は、機能豊富でデザインもスタイリッシュ。コンテンツを新規追加したり、テンプレートを調整したり、ウェブサイトを構成する各種パーツの管理も簡単にできます。ユーザグループごとに、管理画面の操作権限を設定することもできます。また、モジュールを追加して、他のデータセットと連動したり、管理業務を簡易化することも可能です。</p>\r\n<h2>ウェブページ側からコンテンツ管理</h2>\r\n<p>QuickManager（クイックマネージャー）を使えば、サイトをブラウザーで見ながら、ページの内容を編集できます。管理画面を経由せず、ほとんどのコンテンツ要素とテンプレート変数を手軽に編集できます。</p>\r\n<h2>ウェブユーザーに新規コンテンツの作成を許可できます。</h2>\r\n<p>特定のデータ入力作業も、MODXのAPIを利用すれば簡単です。カスタムメイドのデータ入力は、MODX APIを使用しているコードに容易です - フォームをデザインしたり、必要に応じて修正したりできます。（原文：Custom data entry is easy to code using the MODX API - so you can design forms and collect whatever information you need.）</p>', 0, 4, 3, 1, 1, 1, 1144904400, 1, 1158331927, 0, 0, 0, 0, 0, 'Manage Content', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (15, 'document', 'text/html', 'MODXの主な機能', 'MODXの主な機能', '', 'features', '', 1, 0, 0, 0, 1, '', '[!Wayfinder?startId=`[*id*]` &outerClass=`topnav`!]', 1, 4, 7, 1, 1, 1, 1144904400, 1, 1158452722, 0, 0, 0, 1144777367, 1, 'MODXの機能', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (16, 'document', 'text/html', 'AjaxとWeb2.0', 'AjaxとWeb2.0', '', 'ajax', '', 1, 1159264800, 0, 15, 0, '', '<strong>Ajax技術との相性のよさ</strong>\r\n<p>\r\nMODXに実装されている <a href=\"http://mootools.net/\" target=\"_blank\">Mootools</a> javascript libraryライブラリによって、魅力的なサイト作成が可能です。\r\n</p>\r\n<p>\r\nAjaxを活用した検索機能で、このサンプルサイトを検索してみてください。Ajax機能は、フロントエンドの編集機能であるクイックマネージャー機能にも使用されています。\r\n</p>\r\n<p>\r\n洗練された統合機能は、ドキュメントに使用するスクリプトを最小限に抑えます&hellip;単純なページを不必要なスクリプトで膨張させることではありません！\r\n</p>\r\n<strong>最新のWeb2.0</strong>\r\n<p>\r\nコアが直接出力するhtmlコードがほとんどないMODXなら、アクセシビリティの高い、正しいCSSレイアウトのサイト管理だって朝飯前です。ウェブ標準に則ったサイト作成が簡単にできます。（もし必要なら、tableタグに依存したレイアウトも簡単です）\r\n</p>', 1, 4, 1, 1, 1, 1, 1144904400, 1, 1159307504, 0, 0, 0, 0, 0, 'AjaxとWeb2.0', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (22, 'document', 'text/html', 'メニューとリスト', '自由度が高いメニューとリスト', '', 'menus', '', 1, 1159178400, 0, 15, 0, '', '<h2>Your documents - listed how you want them</h2>\r\n<p>\r\n汎用CMSの評価の要となるのが、ナビゲーションコントロールと複数コンテンツのリスト表示。MODXでは、これらのコンテンツコントロールを2つの高機能スニペットに託しました。それがDitto（ディットー）とWayfinder（ウェイファインダー）です。\r\n</p>\r\n<h2>Wayfinder - メニュー生成スニペット</h2>\r\n<p>どのような種類のメニューでも実現します。このサイトでは、Wayfinderはドロップダウンメニューの生成に用いられていますが、他のどんなタイプのメニューやサイトマップも生成可能です。</p>\r\n<h2>Ditto（ディトゥー - 文章のリストアップスニペット）</h2>\r\n<p>新着情報の一覧を生成したり、サイトマップを作ったり、テンプレート変数との組み合わせで関連文書をリストアップしたり、RSSフィードの生成を行ったりします。Wayfinderとは異なるアプローチでナビゲーションを作ることもできます。このサイトでは、簡易ブログのエントリー一覧の生成に使われています。また、サイドバーにも使用されています。</p>\r\n<h2>カスタマイズは無限に可能</h2>\r\n<p>\r\nDittoとWayfinderのオプション、テンプレートを使用しても、満足のいくデザインや効果が得られない場合、独自のルーチンを作ることもできますし、<a href=\"http://modxcms.com/extras.html\">MODXのリポジトリ</a>から他のスニペットを探すこともできます。MODXのメニュータイトル、要約、メニューの場所、そのほか諸々は、APIを利用することによって思い通りのデザインを作ることができます。\r\n</p>', 1, 4, 2, 1, 1, 1, 1144904400, 1, 1160148522, 0, 0, 0, 0, 0, 'メニューとリスト', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (24, 'document', 'text/html', '拡張性豊かなデザインワーク', '拡張性豊かなデザインワーク', '', 'extendable', '', 1, 1159092732, 0, 15, 0, '', '<p>\r\nMODXコミュニティでは、イメージギャラリーやeコマース、その他様々なアドオン部品が <a href=\"http://modxcms.com/extras.html\">リポジトリ</a> で配布されてます。\r\n</p>\r\n<h2>テンプレート変数はデータバインディングが可能</h2>\r\n<p>\r\n「テンプレート変数」は、高機能なカスタムフィールドです。単なるテキストの入力項目ではなく、プログラムと連動した高度なコントロールが可能です。ここでは、コードの実行結果やデータソースによって異なる情報を返す特殊な例をご紹介します。ここではログインメニューを「@バインディング」で実現する例を示します。次のフィールドを追加することでログイン状態に従ってメニューの表示内容を変化させることができます。:\r\n<code>@EVAL if ($modx-&gt;getLoginUserID()) return \'ログアウト\'; else return \'ログイン\';</code>\r\n</p>\r\n<h2>カスタムフォーム</h2>\r\n<p>\r\nカスタムフォームとの関連性を示すために、ウェブユーザー登録システムとログインシステムの呼び出し方法をカスタマイズしてあります。\r\n</p>\r\n<h2>その他</h2>\r\n<h3>\r\n<strong>スマートな概要表示</strong></h3>\r\n<p>\r\n区切りたい位置に&quot;&lt;!-- splitter --&gt;&quot;というタグを入れることで、記事を途中で区切ることができます。また、OL, UL, DIVといった重要なタグが前後に分かれてもタグが閉じるように動作するためレイアウトが崩れることはありません。\r\n</p>', 1, 4, 4, 1, 1, 2, 1144904400, 1, 1159309971, 0, 0, 0, 0, 0, '思い通りの拡張', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (32, 'document', 'text/html', 'デザイン', 'テンプレートデザイン', '', 'design', '', 1, 0, 0, 0, 0, '', '<h3>Credits</h3>\r\n<p>このサンプルコンテンツのテンプレートデザインについて。学習用途向きのシンプルなテンプレートです。</p>', 1, 4, 10, 1, 1, 2, 1144904400, 1, 1160112322, 0, 0, 0, 1144912754, 1, 'Design', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (33, 'document', 'text/html', 'サポート', 'サポート', '', 'geting-help', '', 1, 0, 0, 0, 0, '', '<p>\r\n<a href=\"http://modx.jp/docs.html\" target=\"_blank\">MODX開発チーム</a>はドキュメントの改良に努めています。:\r\n</p>\r\n<ul>\r\n	<li>MODXのテンプレート構築に関する基本的なノウハウについては、<a href=\"http://modx.jp/docs.html\" target=\"_blank\">デザイナーズガイドをご覧ください</a>。 </li>\r\n	<li>MODXを利用したコンテンツの編集方法については、<a href=\"http://modx.jp/docs.html\" target=\"_blank\">コンテンツエディターガイドをご覧ください</a>。 </li>\r\n	<li>管理ツールの詳細とユーザーやグループの設定については、<a href=\"http://modx.jp/docs.html\" target=\"_blank\">アドミニストレーションガイドを精読してください</a>。</li>\r\n	<a href=\"http://modx.jp/docs.html\" target=\"_blank\">デベロッパーズガイドで</a>MODXの構造とAPIについて記述しています。\r\n	<li>もし誰かがこのサイトをインストールしていて、それを見たあなた自身がMODXについて知りたくなったとしたら、<a href=\"http://modx.jp/docs.html\" target=\"_blank\">スタートガイドをご覧ください</a>。</li>\r\n</ul>\r\n<p>\r\nそして<a href=\"http://modx.jp/\" target=\"_blank\">MODXフォーラムを利用すれば、</a>いつでもノウハウを得たり、質疑応答ができます。 \r\n</p>', 1, 4, 8, 1, 1, 2, 1144904400, 2, 1144904400, 0, 0, 0, 0, 0, 'サポート', 0, 0, 0, 0, 0, 0, 0);


REPLACE INTO `{PREFIX}site_content` VALUES (46, 'document', 'text/html', 'ありがとうございます', '', '', 'thank-you', '', 1, 0, 0, 0, 0, '', '<h3>ありがとうございます!</h3>\r\n<p>\r\nコメントありがとうございます。投稿されたコメントを受け付けました。また、あなたの受信トレイにメッセージのコピーが届いているはずです。\r\n</p>\r\n<p>\r\n投稿内容をチェックするよう最善を尽くしておりますのでご安心ください。\r\n</p>', 1, 4, 13, 1, 1, 1, 1159302141, 1, 1159302892, 0, 0, 0, 1159302182, 1, '', 0, 0, 0, 0, 0, 0, 1);

