name: Build Release Package

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip archive
        run: git archive --format=zip HEAD -o evo-${GITHUB_REF_NAME}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: evo-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: true
